server:
  port: 8999

spring:
  application:
    name: strategy-server
  profiles:
    active: dev
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatemennts: true
    maxOpenPreparedStatements: 20

#mybatis
mybatis:
  mapper-locations: classpath:com/starnetsecurity/**/**.xml
  type-aliases-package: classpath:com.starnetsecurity.**.entity

