package com.opensource.usedb.entity;

public class GatewayHandlerEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_handler.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_handler.handler_id
     *
     * @mbggenerated
     */
    private String handlerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_handler.handler_name
     *
     * @mbggenerated
     */
    private String handlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_handler.prev_handler_id
     *
     * @mbggenerated
     */
    private String prevHandlerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gateway_handler.next_handler_id
     *
     * @mbggenerated
     */
    private String nextHandlerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_handler.id
     *
     * @return the value of gateway_handler.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_handler.id
     *
     * @param id the value for gateway_handler.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_handler.handler_id
     *
     * @return the value of gateway_handler.handler_id
     *
     * @mbggenerated
     */
    public String getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_handler.handler_id
     *
     * @param handlerId the value for gateway_handler.handler_id
     *
     * @mbggenerated
     */
    public void setHandlerId(String handlerId) {
        this.handlerId = handlerId == null ? null : handlerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_handler.handler_name
     *
     * @return the value of gateway_handler.handler_name
     *
     * @mbggenerated
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_handler.handler_name
     *
     * @param handlerName the value for gateway_handler.handler_name
     *
     * @mbggenerated
     */
    public void setHandlerName(String handlerName) {
        this.handlerName = handlerName == null ? null : handlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_handler.prev_handler_id
     *
     * @return the value of gateway_handler.prev_handler_id
     *
     * @mbggenerated
     */
    public String getPrevHandlerId() {
        return prevHandlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_handler.prev_handler_id
     *
     * @param prevHandlerId the value for gateway_handler.prev_handler_id
     *
     * @mbggenerated
     */
    public void setPrevHandlerId(String prevHandlerId) {
        this.prevHandlerId = prevHandlerId == null ? null : prevHandlerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gateway_handler.next_handler_id
     *
     * @return the value of gateway_handler.next_handler_id
     *
     * @mbggenerated
     */
    public String getNextHandlerId() {
        return nextHandlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gateway_handler.next_handler_id
     *
     * @param nextHandlerId the value for gateway_handler.next_handler_id
     *
     * @mbggenerated
     */
    public void setNextHandlerId(String nextHandlerId) {
        this.nextHandlerId = nextHandlerId == null ? null : nextHandlerId.trim();
    }
}