package com.opensource.usedb.dao;

import com.opensource.usedb.entity.GatewayHandlerEntity;
import org.apache.ibatis.annotations.Select;

public interface GatewayHandlerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_handler
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_handler
     *
     * @mbggenerated
     */
    int insert(GatewayHandlerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_handler
     *
     * @mbggenerated
     */
    int insertSelective(GatewayHandlerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_handler
     *
     * @mbggenerated
     */
    GatewayHandlerEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_handler
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GatewayHandlerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gateway_handler
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GatewayHandlerEntity record);


    @Select("select id, handler_id handlerId, handler_name handlerName, prev_handler_id prevHandlerId, next_handler_id nextHandlerId " +
            "from gateway_handler where prev_handler_id is null")
    GatewayHandlerEntity getFirstGatewayHandler();

    @Select("select id, handler_id handlerId, handler_name handlerName, prev_handler_id prevHandlerId, next_handler_id nextHandlerId " +
            "from gateway_handler where handler_id = #{handlerId}")
    GatewayHandlerEntity getByHandlerId(String handlerId);
}