package com.opensource.usedb.entity;

public class PaymentChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_channel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_channel.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_channel.channel_id
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_channel.strategy_bean_id
     *
     * @mbggenerated
     */
    private String strategyBeanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_channel.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_channel.id
     *
     * @return the value of payment_channel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_channel.id
     *
     * @param id the value for payment_channel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_channel.channel_name
     *
     * @return the value of payment_channel.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_channel.channel_name
     *
     * @param channelName the value for payment_channel.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_channel.channel_id
     *
     * @return the value of payment_channel.channel_id
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_channel.channel_id
     *
     * @param channelId the value for payment_channel.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_channel.strategy_bean_id
     *
     * @return the value of payment_channel.strategy_bean_id
     *
     * @mbggenerated
     */
    public String getStrategyBeanId() {
        return strategyBeanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_channel.strategy_bean_id
     *
     * @param strategyBeanId the value for payment_channel.strategy_bean_id
     *
     * @mbggenerated
     */
    public void setStrategyBeanId(String strategyBeanId) {
        this.strategyBeanId = strategyBeanId == null ? null : strategyBeanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_channel.enable
     *
     * @return the value of payment_channel.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_channel.enable
     *
     * @param enable the value for payment_channel.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}